project_name: marketxiv
before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go run ./build/generate.go {{.Version}}
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - netbsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w
      - -X 'github.com/BitsOfAByte/marketxiv/backend.Version={{.Version}}'
      - -X 'github.com/BitsOfAByte/marketxiv/backend.Commit={{.Commit}}'
      - -X 'github.com/BitsOfAByte/marketxiv/backend.Date={{.Date}}'
archives:
  - format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  use: github-native
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^build:"
      - "^ci:"

brews:
  - tap:
      owner: BitsOfAByte
      name: marketxiv
    commit_author:
      name: github-actions
      email: actions@github.com
    commit_msg_template: "chore: Brew formula update for version {{ .Tag }}"
    description: |
      FFXIV marketboard for your command line
    homepage: "https://github.com/BitsOfAByte/MarketXIV"
    license: "MIT"

scoop:
  bucket:
    owner: BitsOfAByte
    name: marketxiv
  commit_author:
    name: github-actions
    email: actions@github.com
  commit_msg_template: "chore: Scoop update for version {{ .Tag }}"
  description: |
    FFXIV marketboard for your command line
  homepage: "https://github.com/BitsOfAByte/MarketXIV"
  license: MIT

nfpms:
  - vendor: BitsOfAByte
    id: nfpm
    homepage: https://github.com/BitsOfAByte/MarketXIV
    maintainer: BitsOfAByte
    description: |
      FFXIV marketboard for your command line
    license: MIT
    priority: extra
    section: Utilities
    formats:
      - deb
      - rpm
    provides:
      - marketxiv
    contents:
      - src: ./.build_data/bitsofabyte.repo
        dst: /etc/yum.repos.d/bitsofabyte.repo
        type: config|noreplace
        packager: rpm

      - src: ./.build_data/bitsofabyte.list
        dst: /etc/apt/sources.list.d/bitsofabyte.list
        type: config|noreplace
        packager: deb
    scripts:
      postremove: scripts/post-remove.sh
    rpm:
      compression: xz

publishers:
  - name: "packages.bitsofabyte.dev"
    dir: "{{ dir .ArtifactPath }}"
    ids:
      - nfpm
    cmd: |
      curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/BitsOfAByte/

release:
  github:
    owner: BitsOfAByte
    name: MarketXIV
  prerelease: auto
