project_name: marketxiv
before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go run ./build/generate.go {{.Version}}
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - netbsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ldflags:
      - "-s -w"
      - -X 'github.com/Blooym/marketxiv/backend.Version={{.Version}}'
      - -X 'github.com/Blooym/marketxiv/backend.Commit={{.Commit}}'
      - -X 'github.com/Blooym/marketxiv/backend.Date={{.CommitDate}}'
    mod_timestamp: "{{ .CommitTimestamp }}"
    hooks:
      post:
        - env SKIP_COMPRESS={{ if index .Env "SKIP_COMPRESS"  }}{{ .Env.SKIP_COMPRESS }}{{ else }}false{{ end }} sh ./build/scripts/upx.sh {{ .Path }}

archives:
  - format: zip
    files:
      - LICENSE*
      - README*
      - src: ./.build_data/man/*.gz
        dst: manpages/
        strip_parent: true
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  use: github-native
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^build:"
      - "^ci:"

release:
  github:
    owner: Blooym
    name: MarketXIV
  prerelease: auto
